### ISSUE TITLE
Virtualizor does not support new docker image so  installation of panel fails

### ISSUE THREAD

**Issue by radovanjecmenica** [stefanpejcic/OpenPanel#114]
### OpenPanel version(s) affected

0.1.7

### Description

root@rasa:/usr/local/panel# docker ps
CONTAINER ID   IMAGE     COMMAND                  CREATED         STATUS                                    PORTS     NAMES
8004a1a46fc7   mysql     "docker-entrypoint.s…"   7 minutes ago   Restarting (127) Less than a second ago             openpanel_mysql
root@rasa:/usr/local/panel# serc^C
root@rasa:/usr/local/panel# docker restart  openpanel_mysql 
openpanel_mysql
root@rasa:/usr/local/panel# docker log op
docker: 'log' is not a docker command.
See 'docker --help'
root@rasa:/usr/local/panel# docker logs openpanel_mysql 
Fatal glibc error: CPU does not support x86-64-v2
Fatal glibc error: CPU does not support x86-64-v2
Fatal glibc error: CPU does not support x86-64-v2
Fatal glibc error: CPU does not support x86-64-v2
Fatal glibc error: CPU does not support x86-64-v2
Fatal glibc error: CPU does not support x86-64-v2
Fatal glibc error: CPU does not support x86-64-v2

### How to reproduce

Just install panel on VPS runned by Virtualizor

**Comment by stefanpejcic** [comment]
solved using https://hub.docker.com/r/mysql/mysql-server/ instead of https://hub.docker.com/_/mysql
