### ISSUE TITLE
Ubuntu 24 support

### ISSUE THREAD

**Issue by stefanpejcic** [stefanpejcic/OpenPanel#115]
### OpenPanel version(s) affected

0.1.8

### Description

depends on https://github.com/docker/roadmap/issues/655

### How to reproduce

Currently OpenAdmin and OpenPanel interfaces work on Ubuntu24, but docker with devicemapper does not!

```bash
root@dev-server:~# docker pull mysql
Using default tag: latest
latest: Pulling from library/mysql
fcbdc4090331: Pull complete 
95eb5073c36f: Pull complete 
5e5ba0e6412a: Pull complete 
ee4654eb29b7: Pull complete 
1d2218160b86: Pull complete 
bbe712936412: Pull complete 
4a6efa152609: Pull complete 
0f7c3b67bb2b: Extracting [==================================================>]     321B/321B
7ccd17e83c8a: Download complete 
04bf2c116556: Download complete 
failed to register layer: devicemapper: Error running deviceSuspend dm_task_run failed
```

https://fuchsia.googlesource.com/third_party/github.com/moby/moby/+/refs/tags/v23.0.7/pkg/devicemapper/devmapper_wrapper.go

**Comment by stefanpejcic** [comment]
2 bugs reported:

https://community.openpanel.co/d/51-wordpress-413-request-entity-too-large-file-upload-issue

**Comment by stefanpejcic** [comment]
There will be no support for quotas on Ubuntu24.

This means that you can not limit the disk space usage per user, which makes it suitable only for VPS servers where you own and maintain all the accounts yourself, and not for shared hosting servers.

For shared hosting, we recommend Debian12 which does support quota limiting per user.

**Comment by rajat709** [comment]
Hi @stefanpejcic ,
It was working with 22.04, but now the same issue is appearing again with 22.04. How did you resolve this issue previously? Thanks.

**Comment by stefanpejcic** [comment]
We switched to the newer overlay2 driver that docker supports, and install script will just create XFS partition of 50% available disk space, then mount it for docker with pquota.

Can you share the output from the install script? 😕
