### ISSUE TITLE
`opencli server-on_startup`

### ISSUE THREAD

**Issue by stefanpejcic** [stefanpejcic/OpenPanel#121]
### OpenPanel version(s) affected

0.1.8

### Description

opencli server-on_startup  should not use docker ps but instead list users from database!

### How to reproduce

run: `opencli server-on_startup`

**Comment by stefanpejcic** [comment]
But: it opens 3306 on server restart!

**Comment by stefanpejcic** [comment]
also https://github.com/stefanpejcic/openpanel-docker-cli/blob/main/files/fix_permissions.sh

**Comment by stefanpejcic** [comment]
```stefan@IdeaPad-Slim-3-16ABR8:~/Downloads/openpanel-docker-cli-main$ grep -Rli "docker ps"
firewall/reset.sh
files/fix_permissions.sh
files/remount.sh
user/rename.sh
user/sudo.sh
server/on_startup.sh
backup/create.shOLDDDDDD
backup/index.sh
php/enabled_php_versions.sh
php/install_php_version.sh
```

**Comment by radovanjecmenica** [comment]
Fixed
