### ISSUE TITLE
What is this?

### ISSUE THREAD

**Issue by anjasamar** [stefanpejcic/OpenPanel#143]
### OpenPanel version(s) affected

official web

### Description

https://storage.googleapis.com/openpanel/0.2.1/get.openpanel.co/downloads/0.2.1/debian/openpanel/310/compressed.tar.gz
Error: wget failed for https://storage.googleapis.com/openpanel/0.2.1/get.openpanel.co/downloads/0.2.1/debian/openpanel/310/compressed.tar.gz

### How to reproduce

https://storage.googleapis.com/openpanel/0.2.1/get.openpanel.co/downloads/0.2.1/debian/openpanel/310/compressed.tar.gz
Error: wget failed for https://storage.googleapis.com/openpanel/0.2.1/get.openpanel.co/downloads/0.2.1/debian/openpanel/310/compressed.tar.gz

**Comment by anjasamar** [comment]
NoSuchKeyThe specified key does not exist.No such object: openpanel/0.2.1/get.openpanel.co/downloads/0.2.1/debian/openpanel/310/compressed.tar.gz

**Comment by anjasamar** [comment]
![Uploading Screenshot (8).png…]()

**Comment by anjasamar** [comment]
![Screenshot (8)](https://github.com/stefanpejcic/OpenPanel/assets/21999640/c9ed989a-f6e3-44ac-b2a7-3d04592bb572)

**Comment by stefanpejcic** [comment]
retry the install now

```
bash <(curl -sSL https://get.openpanel.co/)
```
