### ISSUE TITLE
Unable to create csf UI temp file: 'utf-8' codec can't decode byte 0xa9 in position 1422: invalid start byte

### ISSUE THREAD

**Issue by stefanpejcic** [stefanpejcic/OpenPanel#152]
### OpenPanel version(s) affected

0.2.3

### Description

`Unable to create csf UI temp file: 'utf-8' codec can't decode byte 0xa9 in position 1422: invalid start byte` when openinf Firewall Configuration form CSF UI

### How to reproduce

`OpenAdmin > Firewall >Firewall Configuration`

### Possible Solution

encoding

**Comment by radovanjecmenica** [comment]
Forcing UTF-8 encoding in csf.pl file: 

use utf8;
binmode STDIN, ':encoding(UTF-8)';
binmode STDOUT, ':encoding(UTF-8)';
binmode STDERR, ':encoding(UTF-8)';
