### ISSUE TITLE
Installers asks for confirmation but it is invisible

### ISSUE THREAD

**Issue by houtknots** [stefanpejcic/OpenPanel#155]
### OpenPanel version(s) affected

0.2.4

### Description

Currently when trying to install OpenPanel the installer hangs, my believe is that this happens during the APT install part when you type `y + enter` it proceeds, but the the installer does not ask for any confirmation from the user (it is invisible).

### How to reproduce

Install OpenPanel using the Bash script
`bash <(curl -sSL https://get.openpanel.co/)`

### Possible Solution

Add -y option for the apt install options (not sure if this is already done)

### Additional Context

I have installed OpenPanel on Ubuntu 24.04.

**Comment by stefanpejcic** [comment]
Hello, thanks for the info!

can you please run the install again with `--debug` flag?

it will show exact command where it got stuck

**Comment by stefanpejcic** [comment]
Can reproduce only on older installs, where there is newer kernel update and every new service install prompts to reset other services..

On new installs this is ok
