### ISSUE TITLE
Panel not reachable after fresh install and reboot

### ISSUE THREAD

**Issue by WEBDIENSTE** [stefanpejcic/OpenPanel#188]
### OpenPanel version(s) affected

0.2.8

### Description

Fresh system, installed with the official installer on a fresh system.
After a reboot is the panel not reachable anymore. 

### How to reproduce

Fresh install, reboot.

I set up the system multiple times now and everytime the panel is not reachable after the first reboot...

**Comment by stefanpejcic** [comment]
Hello, 
- which OS? 
- which openpanel version you installed - latest 0.2.8 ?
- user or admin panel Is not working after reboot?

**Comment by stefanpejcic** [comment]
Admin panel is set to autostart after reboot: https://github.com/stefanpejcic/OpenPanel/blob/6f2dbe2fb550a2f98359df8e7ce0630910a8d1e6/INSTALL.sh#L1596

User panel Is managed by docker, so that top should start docker servise
