### ISSUE TITLE
CONFIGURATIONS ERROR🕊

### ISSUE THREAD

**Issue by yottajunaid** [stefanpejcic/OpenPanel#199]
Error : Dowloading configuration files from GitHub failed, main conf file /etc/openpanel/openpanel/conf/open panel.config is missing

![20241012_110219.jpg](https://github.com/user-attachments/assets/792ca7cf-f444-4e6d-b058-6670b4073b65)

**Comment by stefanpejcic** [comment]
Hello,

What Is the server location?
Might be network problems, it Is downloading directly from github: https://github.com/stefanpejcic/openpanel-configuration

Repeat with `--retry --debug` flags

**Comment by stefanpejcic** [comment]
https://github.com/stefanpejcic/OpenPanel/commit/4ce6ad9ca449985ecc2665c1e923ccbeba703205

Added retries
