### ISSUE TITLE
Https without ssl

### ISSUE THREAD

**Issue by p3t4rc** [stefanpejcic/OpenPanel#205]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Debian

### Description

Websites unreachable with https when SSL is not installed (should just give browser warning), breaks autologin wordpress feature.

### How to reproduce

Access with https or WP autologin before installing SSL cert.

**Comment by stefanpejcic** [comment]
Might be besst to keep as Is, if we add HTTP in database, when they set ssl im afraid users wont know to replace HTTP with https
