### ISSUE TITLE
Clam AV doesn't work

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#209]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

When I try to start scanning i get this error:

Scan failed: network error

No matter which directory I choose.

### How to reproduce

Try to go to Openpanel.
Go to Clam AV and just try to scan any directory.

**Comment by stefanpejcic** [comment]
thank you for reporting this 🙏
its resolved, im adding it to the update
![2024-10-17_17-08](https://github.com/user-attachments/assets/eba9e93c-a0f7-43e7-a268-a15c15a0e677)
dockerized the clamav service
