### ISSUE TITLE
Front validation needed for domains

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#211]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

when adding invalid domain name, it still refreshes page if "stay on the same page" is not ticked.

#bug

### How to reproduce

Just try to add this domain:
xn--lodaehvb5clj5f.xn--node

**Comment by stefanpejcic** [comment]
added to 0.3.3 milestone

**Comment by stefanpejcic** [comment]
tested with `სთეფან.გა` and `стефан.рс`
![2024-10-21_10-24_1](https://github.com/user-attachments/assets/0caa75f6-3888-446e-b269-f1cb28e6202e)
![2024-10-21_10-24](https://github.com/user-attachments/assets/a072b9c7-0d3c-4f5b-852e-5a93e940e0e5)
