### ISSUE TITLE
PHP.ini save button result window needed

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#213]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

We need message that "changes have made succesfully" and if there is not any changes in the code " there is nothing to save"

or you can't understand save changes button did work or not.

### How to reproduce

Just open php.ini and play with it.

**Comment by stefanpejcic** [comment]
toasts are added across the interface instead of alerts
![2024-10-21_10-41](https://github.com/user-attachments/assets/4c29dabd-594e-4ea5-b0c5-a4729f82c0cc)
