### ISSUE TITLE
Backup destination storage size specifics

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#214]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

<img width="734" alt="Screenshot 2024-10-18 at 15 02 16" src="https://github.com/user-attachments/assets/43396f09-62ad-4f43-b0fe-5e4a7083bf62">

### How to reproduce

it needs measurement units or it's unclear how many gbs or tbs will it have )

**Comment by stefanpejcic** [comment]
the backups section i still under development. Once its finished, we will [write docs first](https://openpanel.com/docs/admin/backups/), then add info tooltips to every field


for now, added `%`:
![2024-10-18_18-45](https://github.com/user-attachments/assets/77283138-4549-480a-b36b-a25c626b66d2)
