### ISSUE TITLE
Interface bugs of Backup Destination

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#215]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

<img width="725" alt="Screenshot 2024-10-18 at 15 13 06" src="https://github.com/user-attachments/assets/fd95e1b6-beb3-4d97-8c09-4fb0b67c23f3">
When I try to add destination I get (#1 issue) this error and it dissapears imeddiately(#2 issue)

<img width="691" alt="Screenshot 2024-10-18 at 15 17 42" src="https://github.com/user-attachments/assets/51d5082e-b4e6-4fd1-878c-f31feae033ad">
#3 issue
unclear erro message and (#2 issue) it dissapears immediately.

### How to reproduce

bkp1.domeni.com
path - /root/bkp-key
Storage limit - 500000
ssh port - 22

**Comment by stefanpejcic** [comment]
what is set as domain here? can you share a screenshot of the entire form when that error is shown 
![image](https://github.com/user-attachments/assets/b57e113e-0961-40a5-bc75-9b62aa92e50a)

Ill reproduce others

**Comment by caesarmind** [comment]
it happens when I use hostname instead of domain

**Comment by stefanpejcic** [comment]
Hostname of the local server or remote?

For local set as it says 127.0.0.1 or localhost
For remote set domain or IP

**Comment by caesarmind** [comment]
> Hostname of the local server or remote?
> 
> For local set as it says 127.0.0.1 or localhost For remote set domain or IP

hostname of remote

**Comment by stefanpejcic** [comment]
Use domain, as the  error says

**Comment by caesarmind** [comment]
<img width="703" alt="Screenshot 2024-10-25 at 23 46 50" src="https://github.com/user-attachments/assets/2aa7e1dd-bab4-4eb4-9740-0cf58ac468a5">

<img width="212" alt="Screenshot 2024-10-25 at 23 49 00" src="https://github.com/user-attachments/assets/d61459ba-85bf-4594-8a3c-2d7930aa9f9c">
Still not fixed.

it worked through the terminal though..

**Comment by caesarmind** [comment]
<img width="1078" alt="Screenshot 2024-10-26 at 00 06 20" src="https://github.com/user-attachments/assets/c77deb14-446c-4fa3-a75e-d8b584275ff2">
As you see destination. has been created, but it's not visible in lists.
