### ISSUE TITLE
Backup Destination lacks field to specify path to directory

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#216]
### OpenPanel version(s) affected

0.3.2.

### What OS are you using?

Ubuntu

### Description

On the backup server I have several drives and different path leads to different disk, so I need field where I will specify path where OP will save backuped information.

### How to reproduce

..

**Comment by stefanpejcic** [comment]
[this is configurable on backup job-level](https://github.com/user-attachments/assets/bd0983f9-e80e-4775-94aa-ee9262d4b62f) - that way you can have 1 destination and multiple jobs with different paths, so in your case:

- backup job 1. - folder on destination: /backups/daily/
- backup job 2. - folder on destination: /var/something/
- etc.
