### ISSUE TITLE
WP Site manager pagespeed issues

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#219]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

<img width="299" alt="Screenshot 2024-10-19 at 18 38 16" src="https://github.com/user-attachments/assets/273055c9-6015-441c-b728-252b9332693e">
#1 Issue
There is no way to update page speed. 
100/100 on mobile/desktop can't be correct, either test was done on empty page.

#2 Needs proper css styling or Mobile/Desktop text are out of scope

### How to reproduce

...

**Comment by stefanpejcic** [comment]
pagespeed API key will be needed to allow users to refresh the data.

Currently it Is only generated when user open that page first time(check site state at the Time From the screenshot should show why its 100) and refreshed nightly.

You Can refresh it manually https://dev.openpanel.com/cli/websites.html#PageSpeed

**Comment by stefanpejcic** [comment]
Regarding styling, as soon as we get some decent budget from Enterprise licenses, we will hire designers to create templates  👍

**Comment by caesarmind** [comment]
Well, I don't think this ISSUE deserves to be closed.
On user side there is clearly false information which shows 100/100 all the time.
If you don't support it, would be better to hide at all.

On the other hand, I think it would be better if you would add option in OpenAdmin where we could set "cron" type behaviour to run "opencli websites-scan -all" or smth like that.
