### ISSUE TITLE
Site manager can't generate screenshot of the website

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#220]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

It can't always generate screenshot of the website.(#1 issue)
When it can't do it, we have an error. (#2 issue) It would be nice if you would have default thumbnail for the times when there is not any scrrenshot.

### How to reproduce

...

**Comment by stefanpejcic** [comment]
set your custom screenshots API: https://dev.openpanel.com/cli/config.html#screenshots

default placeholder and expiration/purge logics should be handled there.

You can also on install set it to `local` so your server will do the generation, and refresh them every 24hrs
