### ISSUE TITLE
Disable/Enable panel modules need openpanel restart

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#221]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

Disable/Enable panel modules need openpanel restart

### How to reproduce

Try to disable how-to widget.
It will not turn off unless you restart openpanel

**Comment by stefanpejcic** [comment]
agreed, this should be the case

**Comment by stefanpejcic** [comment]
added, pushing to 0.3.3 update
![2024-10-21_09-58](https://github.com/user-attachments/assets/e3f70cb3-dff1-4c06-8424-ecd2b391ae11)
