### ISSUE TITLE
disabling widgets disables all enabled modules

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#222]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

When you disable or enable widget for OP. It disables all of modules.

### How to reproduce

Try to disable or enable:
2FA or How to guidelines...

**Comment by stefanpejcic** [comment]
```window.addEventListener('load', updateSelectedModules); // #222```

resolved
