### ISSUE TITLE
Incorectly representing plans OS image

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#227]
### OpenPanel version(s) affected

0.3.2.

### What OS are you using?

Ubuntu

### Description

<img width="564" alt="Screenshot 2024-10-21 at 18 07 02" src="https://github.com/user-attachments/assets/67fcd1cb-e103-4001-b82b-5ebda9a27111">
I am using apahe/mariadb image for basic/deluxe packages and in the package list it says: "custom os".

### How to reproduce

Create package in the same way above...

**Comment by stefanpejcic** [comment]
Hmm, problem appears to be in image name, Can you share output of:
`opwncli plans-list`

**Comment by stefanpejcic** [comment]
Was the plan created from gui or terminal? What did you use as docker image value?

**Comment by caesarmind** [comment]
<img width="787" alt="Screenshot 2024-10-23 at 00 51 34" src="https://github.com/user-attachments/assets/2232f60c-cdbd-4fa2-9942-9788266d880a">
Actually I use basic and deluxe packages in production. they have apache + mariadb combination.

As I said, I think these two are connected:
https://github.com/stefanpejcic/OpenPanel/issues/230

**Comment by stefanpejcic** [comment]
Wait, those Are renmed plans, not created?

If they were created on Enterprise, id would start From 5 not 4

And if they were created on Community, then i dont see any issue, you Can set whatever you want as image


Please provide steps to reproduce on demo site

**Comment by caesarmind** [comment]
It happens on Enterprise edition.
Okay, I found how to reproduce it.

FIrst create package on Enterprise edition.
Then try to rename it, in rename window there is not apache/mariadb to choose, so as far is it can't find it it sets to "none".

**Comment by stefanpejcic** [comment]
reproduced, removed the selection from edit-plan modal, it will now perserve existing image.
![2024-10-23_12-44](https://github.com/user-attachments/assets/3f548cdd-bab1-4262-bbd8-1a02737d6aa9)


adding to update
