### ISSUE TITLE
Package name issue while creating users via terminal

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#230]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

<img width="1238" alt="Screenshot 2024-10-21 at 23 51 06" src="https://github.com/user-attachments/assets/839e5320-3749-45e3-a8bf-9ebafa9f314f">

I have package named as "basic".
It creates issue when creating users via command line with this package.

when I try to create user with "ubuntu_apache_mysql". it works fine.

### How to reproduce

described above...

**Comment by stefanpejcic** [comment]
Put Basic in quotes
`"basic"`

**Comment by stefanpejcic** [comment]
Can you share output of `opencli plans-list`?  Might be some other valuse

**Comment by stefanpejcic** [comment]
Docker image name Is None, that Is the root cause.

What command you used to create plan?

**Comment by caesarmind** [comment]
I created plan via ui.

Seems this issue is connect to:
https://github.com/stefanpejcic/OpenPanel/issues/227

**Comment by caesarmind** [comment]
I created the plan via ui.

Seems this issue is connected to:
https://github.com/stefanpejcic/OpenPanel/issues/227

**Comment by stefanpejcic** [comment]
I cant reproduce it via ui, only when i literally set plan name to 'None'


I'll leave it open, please try again in a few days after the 0.3.3 update
