### ISSUE TITLE
PHP breadcrumbs have broken links

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#235]
### OpenPanel version(s) affected

0.3.2.

### What OS are you using?

Ubuntu

### Description

<img width="1217" alt="Screenshot 2024-10-24 at 20 24 14" src="https://github.com/user-attachments/assets/e589393b-8264-4ce6-8d7c-21258d4a5dfd">
Those links doesn't work properly

### How to reproduce

...

**Comment by stefanpejcic** [comment]
Breadcrumbs are also problematic on mobile: #246 

Might completely disable them, we don't yet have that many pages to consider breadcrumbs useful

**Comment by stefanpejcic** [comment]
php is edited

Breadcrumbs are now disabled on mobile
