### ISSUE TITLE
HTML/JS errors in console on PHP page

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#236]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

<img width="1409" alt="Screenshot 2024-10-24 at 20 26 57" src="https://github.com/user-attachments/assets/67701291-a95a-4434-b0fa-0de7fc10887d">
<img width="1429" alt="Screenshot 2024-10-24 at 20 28 32" src="https://github.com/user-attachments/assets/b81ca833-5894-4399-a8f4-42ca966a6f6c">

### How to reproduce

Just browse from php versions to php options

**Comment by stefanpejcic** [comment]
These just show that there Is no php install in progres, but I'll add better handling 👍

**Comment by stefanpejcic** [comment]
Resolved
