### ISSUE TITLE
Automatically retrieve cPanel backup name [FEATURE REQUEST]

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#239]
### OpenPanel version(s) affected

0.3.2

### What OS are you using?

Ubuntu

### Description

<img width="623" alt="Screenshot 2024-10-24 at 22 25 25" src="https://github.com/user-attachments/assets/6782b5a5-9221-4603-861d-0e31c58cb477">
cPanel checks and automatically retrieves backup name from  /root directory.

It would be nice to see the same here.

### How to reproduce

...

**Comment by caesarmind** [comment]
The same can be done for backup key...

**Comment by stefanpejcic** [comment]
What do you mean by backup key?

**Comment by stefanpejcic** [comment]
added
![2024-10-25_11-42](https://github.com/user-attachments/assets/8429d681-9f34-43f0-9fef-dd4de6237873)


it will look for the new cp backup format `backup-*.tar.gz` in ``'/', '/home', '/root'``
