### ISSUE TITLE
Inode limits aren't displayed properly

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#243]
### OpenPanel version(s) affected

0.3.3

### What OS are you using?

Ubuntu

### Description

<img width="306" alt="Screenshot 2024-10-25 at 23 18 53" src="https://github.com/user-attachments/assets/eeef4ef5-fd60-4c67-8b77-ed0777ae13d0">
It should be 183k/800k as far as I have 800k limit on my package

### How to reproduce

...

**Comment by stefanpejcic** [comment]
Yes, this still shows for the partition, im postponing it in hopes we get a solution for https://github.com/stefanpejcic/OpenPanel/issues/56 as then this wont have to be edited
