### ISSUE TITLE
File Manager - Can't select multiple folder or files on Mac [BUG]

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#247]
### OpenPanel version(s) affected

0.3.3

### What OS are you using?

Ubuntu

### Description

We need opportunity to select several folders or files to manipulate in file manager

### How to reproduce

....

**Comment by stefanpejcic** [comment]
https://openpanel.com/docs/panel/files/#select-all

**Comment by caesarmind** [comment]
It's ok, but if there are lots of file and we need to just select 4-5 file we will have harsh time.

**Comment by stefanpejcic** [comment]
i don't understand why, what is exactly the issue?
Works the same way like files on windows or cpanel:

Ctrl + click on one 
Ctrl + click on another
etc.

**Comment by caesarmind** [comment]
seems like it works on windows, but not on mac...

**Comment by stefanpejcic** [comment]
Oh, nice catch 👏👏

@p3t4rc this might just be a key binding issue, can you extend the js code to work for either ctrl or ⌘ key?

**Comment by p3t4rc** [comment]
Extended, should work the same on MacOS and Windows in next version.
