### ISSUE TITLE
Command for user status

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#248]
### OpenPanel version(s) affected

0.3.3

### What OS are you using?

Ubuntu

### Description

don't u think it would be good if we had command or api that will check user status and provide info if it suspend or not.
I needed this kind of command to create logic for whmcs module

### How to reproduce

...

**Comment by stefanpejcic** [comment]
Sure, `/api/users/USERNAME` should already return that information - I'll check and add to the docs

**Comment by stefanpejcic** [comment]
[`/api/users/USERNAME`](https://dev.openpanel.com/api/users.html#List-single-account) can be used for this, it already returns user data:

```json
{
  "user": {
    "email": "stefan@pejcic.rs",
    "id": 1,
    "plan_id": 1,
    "registered_date": "Mon, 28 Oct 2024 10:03:16 GMT",
    "services": "1,2,3,4,5,6,7,8,9,10,11,12",
    "user_domains": null,
    "username": "grdt5mn0"
  }
}
```


when user is suspended username will have prefix *SUSPENDED_DATE_*:

```json
{
  "user": {
    "email": "stefan@pejcic.rs",
    "id": 1,
    "plan_id": 1,
    "registered_date": "Mon, 28 Oct 2024 10:03:16 GMT",
    "services": "1,2,3,4,5,6,7,8,9,10,11,12",
    "user_domains": null,
    "username": "SUSPENDED_20241028100650_grdt5mn0"
  }
}
````
