### ISSUE TITLE
Cannot Save Changes on Manage User

### ISSUE THREAD

**Issue by Eyecu** [stefanpejcic/OpenPanel#251]
### OpenPanel version(s) affected

0.3.3

### What OS are you using?

Debian

### Description

Trying to change settings in Openadmin - Users - Manage User - Configure...
Change a setting ie backups or Generate 'Domain Visitor' Reports and Press Save Changes and nothing happens

### How to reproduce

As stated on OpenAdmin go To Users, Click on manage for a user and then Click on Configure. Try and change a setting and click Save changes and nothing happens like it isn't even picking up you clicked save changes.

**Comment by stefanpejcic** [comment]
these are still just placeholders for those features, but I'll finish them for next update 👍

**Comment by stefanpejcic** [comment]
Ive left only those that are working: php and sudo access
![2024-10-31_15-01](https://github.com/user-attachments/assets/9a136f59-4ceb-4cb7-9583-863938b7cd5f)



message is moved to the main screen, make sence to display messages right away.
![2024-10-31_15-01_1](https://github.com/user-attachments/assets/cebb47e2-1b9f-41ad-bf76-e384f5f6af12)
