### ISSUE TITLE
Webmail Domain

### ISSUE THREAD

**Issue by Eyecu** [stefanpejcic/OpenPanel#252]
### OpenPanel version(s) affected

0.3.3

### What OS are you using?

Debian

### Description

Cannot Update Webmail Domain

### How to reproduce

On OpenAdmin Go to Email - Email Settings. Under Webmail Domain ( right now defaults to http://ip.address:8080 type in new domain ie https://webmail.domain.com or https://webmail.domain.com/ (tried both) and click save domain. After a few moments it gives a popup saying failed to update webmail domain

**Comment by stefanpejcic** [comment]
Hello, 

the webmail domain should be just the doamin name `webmail.domain.com`

- I will edit the field to do the validation and display error messages

**Comment by Eyecu** [comment]
Hmm you are right i did webmail.domain.com and it updated successfully but then the field reverts back to http://ip.address:8080/

**Comment by stefanpejcic** [comment]
can you stop&start the OpenPanel from `OpenAdmin > Services` page and try again?

if it is still the same, please:

- share output of: `opencli email-webmail`
- share last 4 lines from: `/etc/openpanel/nginx/vhosts/openpanel_proxy.conf`

**Comment by Eyecu** [comment]
output of opencli email-webmail is correct returning webmail.csnode.com

restarting open panel and open admin did not change anything

and the host proxy file is 
`# roundcube
location /webmail {
    return 301 https://webmail.csnode.com;
}
`

After restarting openadmin the panel still reports the webmail URL as http://ip.address:8080

**Comment by stefanpejcic** [comment]
oh, I just remembered something.. that domain was owned by user when we added it for webmail, so in the config it must still have the proxy to IP:8080 that we added manually..

Can you remove it from user account and then add it only as a webmail domain again?

Or temporary add another subdomain to confirm this, like: webmail2.csnode.com

**Comment by Eyecu** [comment]
I was kind of wondering about that, I removed the webmail domain name from the user account. tried setting says it's successful then reverts to HTTP://server.ip:8080 tried setting webmail2.csnode.com and did the same thing. says successful then after a second or two the field reverts back to the server.ip:8080

**Comment by stefanpejcic** [comment]
Output of the command was: `webmail2.csnode.com;`   the `;` at the end indicated that `/` was missing before it, sorry I missed that [in the output here](#issuecomment-2442256094).  Ive added  `/` before the `;` and now /webmail from sidebar in user panel is working.


Webmail button on Emails page displays CORS error in the browser console, I've changed the code to now automatically add the webmail domain to CORS list in the user panel, so  this is now working as well.

**Comment by Eyecu** [comment]
It's usually something small and stupid. Thank You.
