### ISSUE TITLE
Backup Jobs can't retrieve destinations

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#254]
### OpenPanel version(s) affected

0.3.3

### What OS are you using?

Ubuntu

### Description

![image](https://github.com/user-attachments/assets/f28f1900-aa23-4375-9c3b-f6f5b723e82e)

### How to reproduce

Create  remote desination
then try to create backup job

**Comment by caesarmind** [comment]
Also, there is not understatable for what does filters field do there. It doesn't have any sense.
When you choose partial backups interface changes and we can choose desired filters,
on the other hand if filters works with other types of backups, they should be pre-defined and it should be possible to choose and add them.

**Comment by stefanpejcic** [comment]
merging into #255
