### ISSUE TITLE
Invalid respone of backup-job list

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#256]
### OpenPanel version(s) affected

0.3.3

### What OS are you using?

Ubuntu

### Description

While I don't have any backup jobs, tried to run:
opencli backup-job list. it said:

Invalid actino. use: create,edit, or delete.

### How to reproduce

It should return the result saying:
I don't have any backup jobs

**Comment by stefanpejcic** [comment]
merging into #255
