### ISSUE TITLE
Admin notification styling issue

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#259]
### OpenPanel version(s) affected

0.3.4

### What OS are you using?

Ubuntu

### Description

<img width="1101" alt="image" src="https://github.com/user-attachments/assets/5a3e4cda-8123-4eaf-a5df-2a08a415b311">
seems like css issue

### How to reproduce

...

**Comment by stefanpejcic** [comment]
yup, some code from the notifications is interpreted as html.. I'll reopen the #186
