### ISSUE TITLE
phpmyadmin gives token error

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#265]
### OpenPanel version(s) affected

0.3.4

### What OS are you using?

Ubuntu

### Description

phpmyadmin doesn't open from left menu.

### How to reproduce

...

**Comment by stefanpejcic** [comment]
can you please confirm if this affects both nginx and apache?

there was a problem on apache a while back #144 so the logic is a bit different now

**Comment by caesarmind** [comment]
I am not sure. Just check your demo and you will see it on your own.
