### ISSUE TITLE
Weird error when I add domain

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#266]
### OpenPanel version(s) affected

0.3.4

### What OS are you using?

Ubuntu

### Description

When I reach domain limit and try to another domain from panel:
<img width="1088" alt="image" src="https://github.com/user-attachments/assets/ae3321b6-306c-4949-b409-34b4cd0ad341">

I get this

### How to reproduce

..

**Comment by stefanpejcic** [comment]
nice catch!

seems to be caused by [Enhanced Domain addition with error reporting added in v0.3.1](https://openpanel.com/docs/changelog/0.3.1/#-polish)

adding to todo

**Comment by stefanpejcic** [comment]
resolved
![2024-11-07_13-23](https://github.com/user-attachments/assets/1aca26b6-fe3d-42ec-8025-413005eda1db)
