### ISSUE TITLE
Compressed file extraction progress bar

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#270]
### OpenPanel version(s) affected

0.3.4

### What OS are you using?

Ubuntu

### Description

When there is a large compressed file that takes more than a few seconds to extract, you have no way of knowing if the extraction command has been initiated.

The extraction does complete if you wait without taking further action, and the page will refresh at the end. However, there is no indicator to show that the extraction is in progress, which is why users click the extract button multiple times.

### How to reproduce

...

**Comment by stefanpejcic** [comment]
@p3t4rc can we reuse the loader from the copy modal?

**Comment by p3t4rc** [comment]
Thanks for the suggestion, I've added a progress bar for when extraction is running in the background, cheers!
