### ISSUE TITLE
No way to manually start PHP

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#281]
### OpenPanel version(s) affected

0.3.5

### What OS are you using?

Ubuntu

### Description

<img width="1315" alt="image" src="https://github.com/user-attachments/assets/5582d240-892a-46d8-9df3-261fee51ee51">

Why can't I restart php?

### How to reproduce

...

**Comment by stefanpejcic** [comment]
PHP Is started when needed:  when domain is added,  default version changed for new domains, version changed for existing domain, phpini edited, etc. I'll add it as a feature request for update, makes sence to have restart option manually. 👍

systemd is not available in docker containers.

Currently:
- User can add new domain, change version, edit ini.. all of those should start the service: https://openpanel.com/docs/articles/dev-experience/autostart-services/#auto-start-services-in-openpanel
- Admin can restart all services for user with `docker restart USERNAME`
- Admin can edit `/etc/entrypoint.sh` for user to set dome services to auto-start after reboot, even if user has no domains/websites

**Comment by stefanpejcic** [comment]
added to 0.3.7
![2024-11-25_10-31](https://github.com/user-attachments/assets/d16fd597-ef4f-48d1-966d-3c2fa34a0625)
