### ISSUE TITLE
Can't delete suspended account from admin panel

### ISSUE THREAD

**Issue by caesarmind** [stefanpejcic/OpenPanel#289]
### OpenPanel version(s) affected

0.3.6

### What OS are you using?

Ubuntu

### Description

Can't delete suspended account from admin panel

### How to reproduce

...

**Comment by stefanpejcic** [comment]
implemented in 0.3.8 - added to [changelog](https://openpanel.com/docs/changelog/0.3.8/) and `opencli user-delete` command.
