### ISSUE TITLE
Openpanel - Email - manage adding filters

### ISSUE THREAD

**Issue by Eyecu** [stefanpejcic/OpenPanel#290]
### OpenPanel version(s) affected

0.3.7

### What OS are you using?

Debian

### Description

When trying to add:
`require ["copy"];

redirect :copy "user2@not-example.com";`

filter gives a 500 error red banner 
![Screenshot (18)](https://github.com/user-attachments/assets/a46f8c07-6be5-418f-a3c0-2657d5c43761)

### How to reproduce

Create Email: (note this gives an error but still creates the email address) 
After created, go to manage 
go to email filters
enter:
`require ["copy"];

redirect :copy "user2@not-example.com";`

click on save filters.

**Comment by stefanpejcic** [comment]
Strange, couldn't reproduce it:

![2024-12-04_17-16](https://github.com/user-attachments/assets/96a8d96e-ff06-4268-87e6-7643bd19a755)

![2024-12-04_17-17](https://github.com/user-attachments/assets/f156f668-0f3a-41a9-af35-c803738f490d)

can you please share output of that exact error id from the image: `opencli error ID_HERE`

**Comment by Eyecu** [comment]
`root@serv1:~# opencli error 446NlJw0tq3EBWvRtRfgbiFP
ERROR 2002 (HY000): Can't connect to local server through socket '/run/mysqld/mysqld.sock' (2)
ERROR:root:Error Code: 446NlJw0tq3EBWvRtRfgbiFP - 500 Internal Server Error: Error updating file: [Errno 2] No such file or directory: '/home/bcn/mail/relay-radio.com/djs/home/.dovecot.sieve'
`

**Comment by stefanpejcic** [comment]
For now, please execute the following commands:

```
mkdir -p /home/bcn/mail/relay-radio.com/djs/home
touch /home/bcn/mail/relay-radio.com/djs/home/.dovecot.sieve
```
and it should work for that email as well.

---

This situation likely involves an email account created before we introduced the filter feature (November 8, 2024). In version 0.3.5, we added the following change:
> Email folders are now automatically created for new domains.

It seems I overlooked handling the creation of these folders during update for existing emails. I will address this in the upcoming 0.3.8 release, ensuring folders are created if they don't already exist.

**Comment by stefanpejcic** [comment]
added to 0.3.8 update
![2024-12-04_19-03](https://github.com/user-attachments/assets/8b9d28b9-bb99-491c-9ff7-5119db5debd9)

**Comment by Eyecu** [comment]
No i created the email yesterday. But there was no mail directory in /home/bcn
