### ISSUE TITLE
Openpanel dashboard - FTP Accounts listed twice

### ISSUE THREAD

**Issue by Eyecu** [stefanpejcic/OpenPanel#292]
### OpenPanel version(s) affected

0.3.7

### What OS are you using?

Debian

### Description

As you can see in the attached image, FTP Accounts is listed twice in the files section on the open panel dashboard
![Screenshot (20)](https://github.com/user-attachments/assets/35647d64-e083-490b-bc52-20d695d10cd3)

### How to reproduce

Look under files on dashboard

**Comment by stefanpejcic** [comment]
resolved for 0.3.8 - thank you 🙏
