### ISSUE TITLE
Install log upload fails

### ISSUE THREAD

**Issue by stefanpejcic** [stefanpejcic/OpenPanel#71]
### OpenPanel version(s) affected

0.1.5

### Description

Reported by: https://community.openpanel.co/d/30-possible-file-upload-attack

### How to reproduce

Install OpenPanel v 0.1.5

### Possible Solution

Change error message and modify upload method

**Comment by radovanjecmenica** [comment]
Fixed

**Comment by radovanjecmenica** [comment]
Fixed
