### ISSUE TITLE
DELETE modal not functioning properly on admin user delete

### ISSUE THREAD

**Issue by radovanjecmenica** [stefanpejcic/OpenPanel#97]
### OpenPanel version(s) affected

0.1.6

### Description

![image](https://github.com/stefanpejcic/OpenPanel/assets/147708271/0a239487-ec29-48c6-a0c5-f29b2b83cb3d)

### How to reproduce

Create admin user and try to delete it

**Comment by stefanpejcic** [comment]
Same modal on destination delete
